controller_manager:
  ros__parameters:
    update_rate: 400  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

    # Individual controllers for each joint
    leg_front_r_1_controller:
      type: forward_command_controller/MultiInterfaceForwardCommandController
    
    leg_front_r_2_controller:
      type: forward_command_controller/MultiInterfaceForwardCommandController
    
    leg_front_r_3_controller:
      type: forward_command_controller/MultiInterfaceForwardCommandController
    
    leg_front_l_1_controller:
      type: forward_command_controller/MultiInterfaceForwardCommandController
    
    leg_front_l_2_controller:
      type: forward_command_controller/MultiInterfaceForwardCommandController
    
    leg_front_l_3_controller:
      type: forward_command_controller/MultiInterfaceForwardCommandController
    
    leg_back_r_1_controller:
      type: forward_command_controller/MultiInterfaceForwardCommandController
    
    leg_back_r_2_controller:
      type: forward_command_controller/MultiInterfaceForwardCommandController
    
    leg_back_r_3_controller:
      type: forward_command_controller/MultiInterfaceForwardCommandController
    
    leg_back_l_1_controller:
      type: forward_command_controller/MultiInterfaceForwardCommandController
    
    leg_back_l_2_controller:
      type: forward_command_controller/MultiInterfaceForwardCommandController
    
    leg_back_l_3_controller:
      type: forward_command_controller/MultiInterfaceForwardCommandController

# Front Right Leg
leg_front_r_1_controller:
  ros__parameters:
    joint: 'leg_front_r_1'
    interface_names: ['position', 'velocity', 'effort', 'kp', 'kd']

leg_front_r_2_controller:
  ros__parameters:
    joint: 'leg_front_r_2'
    interface_names: ['position', 'velocity', 'effort', 'kp', 'kd']

leg_front_r_3_controller:
  ros__parameters:
    joint: 'leg_front_r_3'
    interface_names: ['position', 'velocity', 'effort', 'kp', 'kd']

# Front Left Leg
leg_front_l_1_controller:
  ros__parameters:
    joint: 'leg_front_l_1'
    interface_names: ['position', 'velocity', 'effort', 'kp', 'kd']

leg_front_l_2_controller:
  ros__parameters:
    joint: 'leg_front_l_2'
    interface_names: ['position', 'velocity', 'effort', 'kp', 'kd']

leg_front_l_3_controller:
  ros__parameters:
    joint: 'leg_front_l_3'
    interface_names: ['position', 'velocity', 'effort', 'kp', 'kd']

# Back Right Leg
leg_back_r_1_controller:
  ros__parameters:
    joint: 'leg_back_r_1'
    interface_names: ['position', 'velocity', 'effort', 'kp', 'kd']

leg_back_r_2_controller:
  ros__parameters:
    joint: 'leg_back_r_2'
    interface_names: ['position', 'velocity', 'effort', 'kp', 'kd']

leg_back_r_3_controller:
  ros__parameters:
    joint: 'leg_back_r_3'
    interface_names: ['position', 'velocity', 'effort', 'kp', 'kd']

# Back Left Leg
leg_back_l_1_controller:
  ros__parameters:
    joint: 'leg_back_l_1'
    interface_names: ['position', 'velocity', 'effort', 'kp', 'kd']

leg_back_l_2_controller:
  ros__parameters:
    joint: 'leg_back_l_2'
    interface_names: ['position', 'velocity', 'effort', 'kp', 'kd']

leg_back_l_3_controller:
  ros__parameters:
    joint: 'leg_back_l_3'
    interface_names: ['position', 'velocity', 'effort', 'kp', 'kd']

joint_state_broadcaster:
  ros__parameters:
    joints:
      - leg_front_r_1
      - leg_front_r_2
      - leg_front_r_3
      - leg_front_l_1
      - leg_front_l_2
      - leg_front_l_3
      - leg_back_r_1
      - leg_back_r_2
      - leg_back_r_3
      - leg_back_l_1
      - leg_back_l_2
      - leg_back_l_3

imu_sensor_broadcaster:
  ros__parameters:
    frame_id: base_link
    sensor_name: imu_sensor
